name: Tests

on: [push]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run PyTests
      run: |
        mkdir report
        pytest --junitxml=./report/testreport.xml
    - name: Upload a Build Artifact
      if: success() || failure()
      uses: actions/upload-artifact@v3.1.2
      with:
        name: test report
        path:  ./report/testreport.xml
