name: Tests

on: [push, workflow_dispatch]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install allure-pytest


    - name: Run PyTests
      run: |
        mkdir report
        pytest --alluredir=allure-results
      continue-on-error: true


    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    - name: Allure Report
      uses: simple-elf/allure-report-action@1.6
      if: always()
      #id: allure-report
      with:
        allure_results: allure-results
        allure_history: allure-history
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
